<h2>16 de diciembre</h2>
<b>1969</b>
Nace Adam Riess, es un astrofísico estadounidense de la Universidad Johns Hopkins y del Instituto de Ciencias del Telescopio Espacial (Space Telescope Science Institute). Es ampliamente conocido por sus investigaciones en cosmología a través del estudio de las supernovas. Obtuvo el Premio Nobel de Física en 2011 junto con Saul Perlmutter y Brian Schmidt por sus trabajos que demuestran la aceleración de la expansión del universo. También en 2006 fue galardonado con el premio Shaw de astronomía por esta misma causa.
